[package]
name = "gtk-qq"
version = "0.1.0"
edition = "2021"

[dependencies.relm4]
git = "https://github.com/Relm4/Relm4.git"
branch = "next"
features = [
    "macros",
    "libadwaita",
]

[profile.release]
lto = true
