[package]
name = "gtk-qq"
version = "0.1.0"
edition = "2021"

[dependencies.relm4]
git = "https://github.com/Relm4/Relm4.git"
# branch = "next"
# May 15, 2022
rev = "65e4b37758fcb95ade347e70acc1efe5a96c0592"
features = [
    "macros",
    "libadwaita",
]

[profile.release]
lto = true
