[package]
name = "gtk-qq"
version = "0.1.0"
edition = "2021"

[dependencies.relm4]
git = "https://github.com/Relm4/Relm4.git"
# next, 2022/05/24
rev = "74659719607331a591dfabf90dd33b7c590bc2fd"
features = [
    "macros",
    "libadwaita",
]

[dependencies.ricq]
git = "https://github.com/lz1998/ricq.git"
# v0.1.5, master, 2022/05/25
rev = "9d771fba83f3d878c4ca0b0673322d7a68b349af"

[dependencies]
tokio = "1.18.2"
rand = "0.8.5"
async-trait = "0.1.53"
once_cell = "1.11.0"

[profile.release]
lto = true
